### ISSUE TITLE
Draft Epic: Review (learn) the cards in my deck

### ISSUE THREAD

**Issue by michaelsnook** [michaelsnook/sunlo-nextjs#11]
- [x] Modify "status" of card-deck memberships ("active" "learned" "ignore")
- [x] "Review" views where you can see just the phrase and then switch and see just its translation
- [x] Cycle through your active cards like this, in like a "review session" (perhaps keep a track of sessions? cards reviewed today, cards moved to "learned", etc.)
- [ ] #77
- [ ] #78

**Comment by michaelsnook** [comment]
will do the advanced space-reps thing, and the add-translation feature in separate chunks of work.
