### ISSUE TITLE
Draft Epic: add types, supabase config, seeds, fragments

### ISSUE THREAD

**Issue by michaelsnook** [michaelsnook/sunlo-nextjs#33]
- [x] add types (create these automatically?)
- [ ] add supabase config (use supabase cli? document)
- [ ] add seeds
- [ ] use fragments for graphql queries
- [x] fix table names, phrase, card, deck
